# Generated by Django 4.1.3 on 2023-11-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognitionmanagermodel',
            name='all_start_value',
            field=models.IntegerField(default='0', verbose_name='All Stars value'),
        ),
    ]
