# Generated by Django 4.1.3 on 2023-02-17 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionTaskManagerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('issue_name', models.CharField(max_length=255, verbose_name='Issue title')),
                ('action_text', models.TextField(blank=True, verbose_name='Issue description')),
                ('solution_text', models.TextField(blank=True, verbose_name='Issue action')),
                ('deadline_date', models.DateField(verbose_name='Deadline date')),
                ('action_status', models.CharField(choices=[('draft', 'DRAFT'), ('canceled', 'CANCELED'), ('completed', 'COMPLETED')], default='draft', max_length=9)),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
                'ordering': ['-action_status', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AssignedToAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actions.actiontaskmanagermodel')),
            ],
            options={
                'ordering': ('action',),
            },
        ),
    ]
