# Generated by Django 4.1.3 on 2023-02-17 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedtoaction',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actiontaskmanagermodel',
            name='action_group',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Action groups'),
        ),
        migrations.AddField(
            model_name='actiontaskmanagermodel',
            name='assigned_user',
            field=models.ManyToManyField(through='actions.AssignedToAction', to=settings.AUTH_USER_MODEL, verbose_name='Assigned'),
        ),
    ]
