# Generated by Django 4.1.3 on 2023-04-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_image',
            field=models.ImageField(blank=True, default='default_image/default_user_image.png', upload_to='profile_image/', verbose_name='Profile image'),
        ),
    ]
