# Generated by Django 4.1.3 on 2023-04-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_usermodel_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_image',
            field=models.ImageField(upload_to='profile_image/', verbose_name='Profile image'),
        ),
    ]
