# Generated by Django 4.1.3 on 2023-04-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_usermodel_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_image',
            field=models.ImageField(default='default_image/default_user_image.png', upload_to='profile_image/', verbose_name='Profile image'),
        ),
    ]
