# Generated by Django 4.1.3 on 2023-02-17 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedToImprovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ('improvement',),
            },
        ),
        migrations.CreateModel(
            name='ImprovementsTaskManagerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('title', models.CharField(max_length=255, verbose_name='Improvement title')),
                ('description', models.TextField(blank=True, verbose_name='Improvement description')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('deadline_date', models.DateField(verbose_name='Deadline date')),
                ('status', models.CharField(choices=[('to_do', 'TO DO'), ('in_progress', 'IN PROGRESS'), ('review', 'REVIEW'), ('done', 'DONE')], default='To Do', max_length=12)),
                ('assigned_user', models.ManyToManyField(through='improvements.AssignedToImprovement', to=settings.AUTH_USER_MODEL, verbose_name='Assigned')),
                ('group', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Improvement group')),
            ],
            options={
                'verbose_name': 'Improvement ',
                'verbose_name_plural': 'Improvements',
                'ordering': ['status'],
            },
        ),
        migrations.AddField(
            model_name='assignedtoimprovement',
            name='improvement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='improvements.improvementstaskmanagermodel'),
        ),
        migrations.AddField(
            model_name='assignedtoimprovement',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
