# Generated by Django 4.1.3 on 2023-02-17 08:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceManagerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_status', models.CharField(choices=[('present', 'PRESENT'), ('absent', 'ABSENT'), ('excused', 'EXCUSED'), ('on_vacation', 'ON_VACATION'), ('comes_later', 'COMES_LATER')], default='present', max_length=11)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='WOR_date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='week start date')),
                ('end_date', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='week end date')),
                ('week_number', models.IntegerField(default='0', verbose_name='Week')),
            ],
            options={
                'ordering': ['week_number'],
            },
        ),
        migrations.CreateModel(
            name='WeekAttendanceRoleManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_group', models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Role`s group')),
                ('week_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.wor_date')),
            ],
            options={
                'ordering': ['week_id'],
            },
        ),
    ]
