# Generated by Django 4.1.3 on 2023-02-17 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekattendancerolemanager',
            name='wor_engager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wor_engager', to=settings.AUTH_USER_MODEL, verbose_name='WOR Engager'),
        ),
        migrations.AddField(
            model_name='weekattendancerolemanager',
            name='wor_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wor_leader', to=settings.AUTH_USER_MODEL, verbose_name='WOR Learder'),
        ),
        migrations.AddField(
            model_name='attendancemanagermodel',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.wor_date'),
        ),
        migrations.AddField(
            model_name='attendancemanagermodel',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
